// 배포 전 빌드: dist 폴더에 빌드 산출물 생성 (원본 파일 유지)
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { minify } = require('terser');
const cssnano = require('cssnano');
const postcss = require('postcss');
const sharp = require('sharp');

const ROOT_DIR = path.join(__dirname, '..');
const ASSETS_DIR = path.join(ROOT_DIR, 'assets');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const BUILD_REPORT_FILENAME = 'build-report.json';
const CLOUDFLARE_HEADERS_FILENAME = '_headers';
const CLOUDFLARE_REDIRECTS_FILENAME = '_redirects';
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg']);
const LARGE_SOURCE_IMAGE_BYTES = 1024 * 1024;
const LARGE_DIST_IMAGE_BYTES = 1024 * 1024;
const SENSITIVE_DIST_PATHS = [
  'firestore.rules',
  'firebase.json',
  '.firebaserc',
  'storage.rules',
  'serviceAccountKey.json',
  'functions',
  'scripts',
  'node_modules'
];
const ARCHIVE_ASSET_DIR_PATTERN = /(^|\/)(raw|original|orig|archive|backup|bak|test|unused|old|design|psd)(\/|$)/i;
const ORIGINAL_RASTER_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg']);
const PRESERVED_ROOT_ORIGINALS = new Set([
  'favicon.png',
  'logo.png',
  'logo-dark.png',
  'footer_logo.png',
  'darkmode.png',
  'lightmode.png'
]);
/** Legacy optional assets — not required for build; excluded from policy warnings. */
const LEGACY_OPTIONAL_ROOT_ASSETS = new Set([
  'banner_main.png',
  'banner_main.webp'
]);
const LEGACY_OPTIONAL_ROOT_STEMS = new Set([
  'banner_main'
]);
const REQUIRED_SOURCE_ORIGINALS = [
  'main.png',
  'favicon.png',
  'logo.png',
  'logo-dark.png',
  'footer_logo.png',
  'darkmode.png',
  'lightmode.png'
];
const RUNTIME_WEBP_SOURCE_ORIGINALS = new Set([
  'main.png'
]);
const FORCED_WEBP_OUTPUTS = new Set([
  'main.webp'
]);
const WEBP_PREFERRED_ASSET_DIRS = [
  'popup',
  'story',
  'contact',
  'course',
  'class',
  'instructors/curriculum',
  'instructors/posters',
  'instructors/books'
];

function createBuildReport({ strictMode, removeDev, version }) {
  return {
    version,
    generatedAt: new Date().toISOString(),
    strictMode,
    removeDevCode: removeDev,
    steps: {
      warnings: [],
      totalWarnings: 0
    },
    minify: {
      css: {
        fallbackCopied: false,
        error: null
      },
      js: {
        fallbackFiles: [],
        totalProcessed: 0
      }
    },
    imageValidation: {
      missingReferences: [],
      requiredMissing: [],
      distAssetReferences: [],
      archiveLikeDirectories: [],
      largeSourceImages: [],
      duplicatePairs: [],
      missingWebpCounterparts: []
    },
    imageOutput: {
      skippedOriginals: [],
      skippedWebpDuplicates: [],
      preservedOriginals: [],
      allowedNonWebpDistFiles: [],
      largeDistImages: []
    }
  };
}

function writeBuildReport(report) {
  const buildReportPath = path.join(DIST_DIR, BUILD_REPORT_FILENAME);
  fs.writeFileSync(buildReportPath, JSON.stringify(report, null, 2));
  console.log(`✅ 빌드 리포트 저장: ${buildReportPath}`);
}

function writeVersionJson(version) {
  const versionPath = path.join(DIST_DIR, 'version.json');
  const payload = {
    version,
    generatedAt: new Date().toISOString()
  };
  fs.writeFileSync(versionPath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  console.log('✅ version.json 생성 완료');
}

function writeCloudflarePagesHeaders() {
  const headersPath = path.join(DIST_DIR, CLOUDFLARE_HEADERS_FILENAME);
  const content = [
    '# Generated by scripts/prebuild.js for Cloudflare Pages.',
    '# Keep firebase.json hosting.headers in sync when cache policy changes.',
    '',
    '/sitemap.xml',
    '  Content-Type: application/xml; charset=utf-8',
    '  Cache-Control: no-cache',
    '',
    '/robots.txt',
    '  Content-Type: text/plain; charset=utf-8',
    '  Cache-Control: no-cache',
    '',
    '/version.json',
    '  Cache-Control: no-cache, no-store, must-revalidate',
    '  Content-Type: application/json; charset=utf-8',
    '',
    '/sw.js',
    '  Cache-Control: no-cache, no-store, must-revalidate',
    '  Content-Type: application/javascript; charset=utf-8',
    '',
    '/manifest.webmanifest',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: application/manifest+json; charset=utf-8',
    '',
    '/offline.html',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: text/html; charset=utf-8',
    '',
    '/assets/icons/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.js',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: application/javascript; charset=utf-8',
    '',
    '/assets/*.css',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: text/css; charset=utf-8',
    '',
    '/assets/*.png',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.jpg',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.jpeg',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.gif',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.svg',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.webp',
    '  Content-Type: image/webp',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.csv',
    '  Cache-Control: public,max-age=86400',
    '  X-Content-Type-Options: nosniff',
    '',
    '/assets/*.pdf',
    '  Cache-Control: public,max-age=86400',
    '  X-Content-Type-Options: nosniff',
    '',
    '/*.woff2',
    '  Content-Type: font/woff2',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  Access-Control-Allow-Origin: *',
    '',
    '/*.woff',
    '  Content-Type: font/woff',
    '  Cache-Control: public,max-age=31536000,immutable',
    '  Access-Control-Allow-Origin: *',
    '',
    '/',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: text/html; charset=utf-8',
    '',
    '/*.html',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: text/html; charset=utf-8',
    '',
    '/assets/partials/*.html',
    '  Cache-Control: no-cache, must-revalidate',
    '  Content-Type: text/html; charset=utf-8',
    ''
  ].join('\n');

  fs.writeFileSync(headersPath, content, 'utf8');
  console.log('✅ Cloudflare Pages _headers 생성 완료');
}

function writeCloudflareRedirects() {
  const redirectsPath = path.join(DIST_DIR, CLOUDFLARE_REDIRECTS_FILENAME);
  // Cloudflare Pages serves *.html at extensionless paths (schedule-images.html -> /schedule-images).
  // Do NOT add /schedule-images -> schedule-images.html rewrites: internal .html fetch 308s back
  // to /schedule-images and causes ERR_TOO_MANY_REDIRECTS on production.
  const content = '\n';
  fs.writeFileSync(redirectsPath, content, 'utf8');
  console.log('✅ Cloudflare Pages _redirects 생성 완료');
}

function removeSensitiveDistFiles() {
  let removed = 0;
  for (const relPath of SENSITIVE_DIST_PATHS) {
    const targetPath = path.join(DIST_DIR, ...relPath.split('/'));
    if (!fs.existsSync(targetPath)) continue;
    fs.rmSync(targetPath, { recursive: true, force: true });
    removed++;
    console.log(`🧹 public 노출 제외: dist/${relPath}`);
  }
  if (removed === 0) {
    console.log('✅ public 제외 대상 운영 파일 없음');
  }
}

// dist 폴더 초기화
function toPosixPath(filePath) {
  return filePath.split(path.sep).join('/');
}

function walkFiles(dirPath, shouldSkipDir = () => false) {
  const files = [];
  if (!fs.existsSync(dirPath)) return files;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      if (shouldSkipDir(fullPath, entry.name)) continue;
      files.push(...walkFiles(fullPath, shouldSkipDir));
    } else if (entry.isFile()) {
      files.push(fullPath);
    }
  }
  return files;
}

function getAssetRelativePath(filePath) {
  return toPosixPath(path.relative(ASSETS_DIR, filePath));
}

function getSourceReferenceFiles() {
  const sourceRoots = [
    ROOT_DIR,
    path.join(ROOT_DIR, 'members'),
    path.join(ASSETS_DIR, 'partials'),
    path.join(ASSETS_DIR, 'css'),
    path.join(ASSETS_DIR, 'js')
  ];
  const seen = new Set();
  const files = [];
  const allowedExts = new Set(['.html', '.css', '.js']);

  for (const sourceRoot of sourceRoots) {
    const discovered = walkFiles(sourceRoot, (fullPath, name) => {
      const rel = toPosixPath(path.relative(ROOT_DIR, fullPath));
      return (
        name === '.git' ||
        name === 'node_modules' ||
        name === 'dist' ||
        name === 'functions' ||
        name === 'scripts' ||
        rel.startsWith('scripts/')
      );
    });

    for (const filePath of discovered) {
      const ext = path.extname(filePath).toLowerCase();
      if (!allowedExts.has(ext)) continue;
      const rel = toPosixPath(path.relative(ROOT_DIR, filePath));
      if (seen.has(rel)) continue;
      seen.add(rel);
      files.push(filePath);
    }
  }

  return files;
}

function collectSourceImageReferences() {
  const refs = new Map();
  const assetImageRefPattern = /((?:https?:\/\/[^"'`\s)<>]+)?\/assets\/[^"'`\s)<>]+\.(?:png|jpe?g|webp|svg))(?:[?#][^"'`\s)<>]*)?/gi;

  for (const filePath of getSourceReferenceFiles()) {
    const relFile = toPosixPath(path.relative(ROOT_DIR, filePath));
    let content = '';
    try {
      content = fs.readFileSync(filePath, 'utf8');
    } catch (error) {
      console.warn(`  ⚠️  Image reference scan skipped ${relFile}: ${error.message}`);
      continue;
    }

    const lines = content.split(/\r?\n/);
    lines.forEach((line, index) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*')) return;
      if (/\bplaceholder\s*=|placeholder:/i.test(line)) return;

      for (const match of line.matchAll(assetImageRefPattern)) {
        let url = match[1].split(/[?#]/)[0];
        if (/^https?:\/\//i.test(url)) {
          try {
            url = new URL(url).pathname;
          } catch (_) {
            continue;
          }
        }
        const assetRel = url.replace(/^\/assets\//, '');
        if (!assetRel || assetRel.includes('${') || assetRel.includes('*')) continue;

        const key = `assets/${assetRel}`;
        if (!refs.has(key)) {
          refs.set(key, {
            path: key,
            references: []
          });
        }
        refs.get(key).references.push(`${relFile}:${index + 1}`);
      }
    });
  }

  return [...refs.values()].sort((a, b) => a.path.localeCompare(b.path, 'en'));
}

function collectDistAssetReferences() {
  const refs = new Map();
  const distAssetRefPattern = /\/dist\/assets\/[^"'`\s)<>]+/gi;

  for (const filePath of getSourceReferenceFiles()) {
    const relFile = toPosixPath(path.relative(ROOT_DIR, filePath));
    let content = '';
    try {
      content = fs.readFileSync(filePath, 'utf8');
    } catch (error) {
      console.warn(`  ⚠️  dist asset reference scan skipped ${relFile}: ${error.message}`);
      continue;
    }

    const lines = content.split(/\r?\n/);
    lines.forEach((line, index) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*')) return;

      for (const match of line.matchAll(distAssetRefPattern)) {
        const pathValue = match[0];
        if (!refs.has(pathValue)) {
          refs.set(pathValue, {
            path: pathValue,
            references: []
          });
        }
        refs.get(pathValue).references.push(`${relFile}:${index + 1}`);
      }
    });
  }

  return [...refs.values()].sort((a, b) => a.path.localeCompare(b.path, 'en'));
}

function getOriginalPreserveReason(relAssetPath) {
  const normalized = toPosixPath(relAssetPath);
  const ext = path.extname(normalized).toLowerCase();
  if (!ORIGINAL_RASTER_EXTENSIONS.has(ext)) return '';
  if (PRESERVED_ROOT_ORIGINALS.has(normalized)) {
    return 'allowlisted-root-logo-favicon-or-theme-asset';
  }
  if (normalized.startsWith('icons/')) {
    return 'allowlisted-pwa-install-icon';
  }
  if (normalized.startsWith('instructors/profile/')) {
    return 'allowlisted-instructor-profile-photo';
  }
  return '';
}

function isWebpPreferredAssetPath(relAssetPath) {
  const normalized = toPosixPath(relAssetPath);
  return WEBP_PREFERRED_ASSET_DIRS.some((dirPath) => (
    normalized === dirPath || normalized.startsWith(`${dirPath}/`)
  ));
}

function getWebpRelPath(relAssetPath) {
  return toPosixPath(relAssetPath).replace(/\.(png|jpg|jpeg)$/i, '.webp');
}

function findSourceOriginalCounterpartForWebp(relAssetPath) {
  if (path.extname(relAssetPath).toLowerCase() !== '.webp') return '';
  const withoutExt = relAssetPath.replace(/\.webp$/i, '');
  for (const ext of ORIGINAL_RASTER_EXTENSIONS) {
    const candidateRel = `${withoutExt}${ext}`;
    const candidatePath = path.join(ASSETS_DIR, ...candidateRel.split('/'));
    if (fs.existsSync(candidatePath)) {
      return `assets/${candidateRel}`;
    }
  }
  return '';
}

function validateImageAssetPolicy(report) {
  console.log('🖼️  이미지 에셋 정책 검증 중...');
  // R2 public HTTPS URLs (public/popup/, public/instructors/...) are not scanned here.
  // collectSourceImageReferences() only matches paths containing /assets/.

  const distRefs = collectDistAssetReferences();
  for (const ref of distRefs) {
    report.imageValidation.distAssetReferences.push(ref);
    console.warn(`  ⚠️  dist 경로 참조 금지: ${ref.path} (${ref.references.join(', ')})`);
  }

  for (const relAsset of REQUIRED_SOURCE_ORIGINALS) {
    const fullPath = path.join(ASSETS_DIR, relAsset);
    if (!fs.existsSync(fullPath)) {
      const item = {
        path: `assets/${relAsset}`,
        message: `${relAsset} is required as a source original by the local image asset policy.`
      };
      report.imageValidation.requiredMissing.push(item);
      console.error(`  ❌ ${item.path} 누락: ${item.message}`);
    }
  }

  const refs = collectSourceImageReferences();
  for (const ref of refs) {
    const relAssetPath = ref.path.replace(/^assets\//, '');
    const fullPath = path.join(ASSETS_DIR, ...relAssetPath.split('/'));
    if (!fs.existsSync(fullPath)) {
      const generatedFrom = findSourceOriginalCounterpartForWebp(relAssetPath);
      if (generatedFrom) {
        continue;
      }
      report.imageValidation.missingReferences.push(ref);
      console.warn(`  ⚠️  누락된 이미지 참조: ${ref.path} (${ref.references.join(', ')})`);
    }
  }

  const assetFiles = walkFiles(ASSETS_DIR, (fullPath, name) => name === 'css' || name === 'js');
  const imageFiles = assetFiles.filter((filePath) => IMAGE_EXTENSIONS.has(path.extname(filePath).toLowerCase()));

  for (const filePath of imageFiles) {
    const rel = getAssetRelativePath(filePath);
    if (RUNTIME_WEBP_SOURCE_ORIGINALS.has(rel)) {
      continue;
    }
    if (LEGACY_OPTIONAL_ROOT_ASSETS.has(rel)) {
      continue;
    }
    const stats = fs.statSync(filePath);
    if (stats.size > LARGE_SOURCE_IMAGE_BYTES) {
      report.imageValidation.largeSourceImages.push({
        path: `assets/${rel}`,
        sizeBytes: stats.size,
        sizeMB: Number((stats.size / 1024 / 1024).toFixed(2))
      });
    }
  }

  const assetDirs = walkFiles(ASSETS_DIR)
    .map((filePath) => path.dirname(getAssetRelativePath(filePath)))
    .filter((dirPath, index, all) => dirPath && all.indexOf(dirPath) === index)
    .sort((a, b) => a.localeCompare(b, 'en'));

  report.imageValidation.archiveLikeDirectories = assetDirs
    .filter((dirPath) => ARCHIVE_ASSET_DIR_PATTERN.test(dirPath))
    .map((dirPath) => `assets/${dirPath}`);

  const byStem = new Map();
  for (const filePath of imageFiles) {
    const ext = path.extname(filePath).toLowerCase().slice(1);
    const dir = path.dirname(getAssetRelativePath(filePath));
    const stem = path.basename(filePath, path.extname(filePath));
    const key = dir === '.' ? stem : `${dir}/${stem}`;
    if (!byStem.has(key)) {
      byStem.set(key, { path: `assets/${key}`, extensions: new Set() });
    }
    byStem.get(key).extensions.add(ext);
  }

  report.imageValidation.duplicatePairs = [...byStem.values()]
    .filter((item) => item.extensions.size > 1)
    .filter((item) => !LEGACY_OPTIONAL_ROOT_STEMS.has(item.path.replace(/^assets\//, '')))
    .map((item) => ({
      path: item.path,
      extensions: [...item.extensions].sort()
    }))
    .sort((a, b) => a.path.localeCompare(b.path, 'en'));

  report.imageValidation.missingWebpCounterparts = imageFiles
    .map((filePath) => getAssetRelativePath(filePath))
    .filter((rel) => ORIGINAL_RASTER_EXTENSIONS.has(path.extname(rel).toLowerCase()))
    .filter((rel) => isWebpPreferredAssetPath(rel))
    .filter((rel) => !fs.existsSync(path.join(ASSETS_DIR, ...getWebpRelPath(rel).split('/'))))
    .map((rel) => ({
      source: `assets/${rel}`,
      expected: `assets/${getWebpRelPath(rel)}`
    }))
    .sort((a, b) => a.source.localeCompare(b.source, 'en'));

  if (report.imageValidation.largeSourceImages.length > 0) {
    console.warn(`  ⚠️  1MB 초과 원본 이미지 ${report.imageValidation.largeSourceImages.length}개`);
    report.imageValidation.largeSourceImages.slice(0, 8).forEach((item) => {
      console.warn(`     - ${item.path}: ${item.sizeMB}MB`);
    });
  }

  if (report.imageValidation.archiveLikeDirectories.length > 0) {
    console.warn(`  ⚠️  assets 내부 archive/raw/test 계열 폴더 ${report.imageValidation.archiveLikeDirectories.length}개`);
    report.imageValidation.archiveLikeDirectories.forEach((dirPath) => console.warn(`     - ${dirPath}`));
  }

  if (report.imageValidation.duplicatePairs.length > 0) {
    console.warn(`  ⚠️  PNG/JPG/WebP 중복 후보 ${report.imageValidation.duplicatePairs.length}개`);
  }
  if (report.imageValidation.missingWebpCounterparts.length > 0) {
    console.warn(`  ⚠️  WebP 우선 폴더의 소스 WebP 누락 ${report.imageValidation.missingWebpCounterparts.length}개 (prebuild에서 dist WebP 생성 가능)`);
  }

  const errorCount = (
    report.imageValidation.requiredMissing.length +
    report.imageValidation.missingReferences.length +
    report.imageValidation.distAssetReferences.length
  );
  if (errorCount > 0) {
    throw new Error(`Image asset validation failed: ${errorCount} missing required/reference asset(s).`);
  }

  console.log('✅ 이미지 에셋 정책 검증 완료');
}

function distPathAccessible(targetPath) {
  try {
    fs.accessSync(targetPath, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function forceRemovePath(targetPath) {
  if (!targetPath) return true;

  if (process.platform === 'win32') {
    const winPath = targetPath.replace(/\//g, '\\');
    try {
      execSync(`cmd /c attrib -R -S -H "${winPath}" /S /D`, { stdio: 'ignore' });
    } catch (_) {}
    try {
      execSync(`cmd /c del /f /q "${winPath}"`, { stdio: 'ignore' });
    } catch (_) {}
    try {
      execSync(`cmd /c rmdir /s /q "${winPath}"`, { stdio: 'ignore' });
    } catch (_) {}
  }

  if (!distPathAccessible(targetPath)) return true;

  try {
    fs.rmSync(targetPath, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
  } catch (_) {}

  return !distPathAccessible(targetPath);
}

function tryWriteViaTemp(tempPath, destPath, content) {
  try {
    fs.mkdirSync(path.dirname(tempPath), { recursive: true });
    fs.writeFileSync(tempPath, content, 'utf8');
    forceRemovePath(destPath);
    fs.renameSync(tempPath, destPath);
    return true;
  } catch (_) {
    try {
      forceRemovePath(destPath);
      fs.copyFileSync(tempPath, destPath);
      fs.unlinkSync(tempPath);
      return true;
    } catch (_) {
      try {
        fs.unlinkSync(tempPath);
      } catch (_) {}
      return false;
    }
  }
}

function writeDistFileSafely(destPath, content) {
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  const tempCandidates = [
    path.join(path.dirname(destPath), `.${path.basename(destPath)}.${process.pid}.tmp`),
    path.join(DIST_DIR, `.${path.basename(destPath)}.${process.pid}.tmp`)
  ];

  for (const tempPath of tempCandidates) {
    for (let attempt = 0; attempt < 5; attempt += 1) {
      if (tryWriteViaTemp(tempPath, destPath, content)) {
        return true;
      }
      const start = Date.now();
      while (Date.now() - start < 200) {
        // brief wait before retry
      }
    }
  }

  return false;
}

function writeScheduleImagesCleanUrlContent(content) {
  const cleanDest = path.join(DIST_DIR, 'schedule-images', 'index.html');
  if (writeDistFileSafely(cleanDest, content)) {
    console.log('✅ /schedule-images clean URL 생성 (dist/schedule-images/index.html)');
    return true;
  }

  console.log('ℹ️  dist/schedule-images/index.html 미생성 — Cloudflare pretty URL 또는 firebase.json rewrite 사용');
  return false;
}

function initDistDir() {
  console.log('📁 빌드 디렉토리 초기화 중...');
  forceRemovePath(path.join(DIST_DIR, 'schedule-images', 'index.html'));
  forceRemovePath(path.join(DIST_DIR, 'schedule-images'));
  if (fs.existsSync(DIST_DIR)) {
    try {
      // Windows에서 파일이 사용 중일 수 있으므로 재시도 로직 추가
      let retries = 3;
      while (retries > 0) {
        try {
          fs.rmSync(DIST_DIR, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 });
          break;
        } catch (err) {
          retries--;
          if (retries === 0) {
            // 삭제 실패 시 경고만 출력하고 계속 진행 (기존 파일 덮어쓰기)
            console.warn('⚠️  dist 폴더 삭제 실패. 기존 파일을 덮어쓰기 모드로 진행합니다.');
            console.warn('   원인:', err.message);
            break;
          }
          console.log(`   ⚠️  삭제 재시도 중... (${3 - retries}/3)`);
          // 잠시 대기 후 재시도 (동기 방식)
          const start = Date.now();
          while (Date.now() - start < 500) {
            // 500ms 대기
          }
        }
      }
    } catch (err) {
      // 최종 실패 시에도 경고만 출력하고 계속 진행
      console.warn('⚠️  dist 폴더 삭제 실패. 기존 파일을 덮어쓰기 모드로 진행합니다.');
      console.warn('   원인:', err.message);
    }
  }
  // 폴더가 없으면 생성, 있으면 그대로 사용
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }
  console.log('✅ 빌드 디렉토리 준비 완료');
}

const LOCAL_CSS_IMPORT_PATTERN = /@import\s+(?:url\s*\(\s*)?['"]?([^'")]+)['"]?\s*\)?\s*;/gi;

function isExternalCssImport(href) {
  const normalized = String(href || '').trim();
  return /^https?:\/\//i.test(normalized) || normalized.startsWith('//');
}

function resolveCssImportPath(importHref, fromDir) {
  const href = String(importHref || '').trim().split(/[?#]/)[0];
  if (!href || isExternalCssImport(href)) {
    return null;
  }
  if (href.startsWith('/assets/css/')) {
    return path.join(ASSETS_DIR, 'css', href.slice('/assets/css/'.length));
  }
  if (href.startsWith('/')) {
    return path.join(ROOT_DIR, href.replace(/^\//, ''));
  }
  return path.resolve(fromDir, href);
}

function findLocalCssImports(content) {
  const imports = [];
  if (typeof content !== 'string' || !content.includes('@import')) {
    return imports;
  }

  for (const match of content.matchAll(LOCAL_CSS_IMPORT_PATTERN)) {
    const href = String(match[1] || '').trim();
    if (!href || isExternalCssImport(href)) {
      continue;
    }
    imports.push({ full: match[0], href });
  }

  return imports;
}

function inlineLocalCssImports(content, baseDir, seen = new Set()) {
  return content.replace(LOCAL_CSS_IMPORT_PATTERN, (fullMatch, importHref) => {
    const targetPath = resolveCssImportPath(importHref, baseDir);
    if (!targetPath) {
      return fullMatch;
    }

    const normalized = path.normalize(targetPath);
    if (seen.has(normalized)) {
      return '';
    }
    if (!fs.existsSync(normalized)) {
      throw new Error(`CSS import target not found: ${importHref} (resolved to ${targetPath})`);
    }

    seen.add(normalized);
    const imported = fs.readFileSync(normalized, 'utf8');
    const inlined = inlineLocalCssImports(imported, path.dirname(normalized), seen);
    return `${inlined}\n`;
  });
}

function collectCssFileList() {
  const baseCssFiles = [
    'assets/css/base/variables.css',
    'assets/css/base/reset.css',
    'assets/css/base/typography.css',
    'assets/css/base/utilities.css',
    'assets/css/base/layout.css'
  ];
  const componentCssFiles = [
    'assets/css/components/button.css',
    'assets/css/components/card.css',
    'assets/css/components/header.css',
    'assets/css/components/footer.css',
    'assets/css/components/skeleton.css',
    'assets/css/components/dashboard-skeleton.css',
    'assets/css/components/status.css',
    'assets/css/components/modal.css',
    'assets/css/components/dashboard-modal.css',
    'assets/css/components/toast.css',
    'assets/css/components/pagination.css',
    'assets/css/components/filter.css',
    'assets/css/components/dash-back.css',
    'assets/css/components/form.css',
    'assets/css/components/kakao-channel.css'
  ];

  const pagesDir = path.join(ASSETS_DIR, 'css', 'pages');
  const preferredPageOrder = [
    'courses-all.css',
    'course-detail.css',
    'course.css',
    'instructor.css',
    'public.css',
    'notfound.css',
    'admin.css',
    'admin-courses.css',
    'student.css'
  ];

  let pageCssFiles = [];
  if (fs.existsSync(pagesDir)) {
    const discoveredPageFiles = fs.readdirSync(pagesDir)
      .filter((name) => name.endsWith('.css'))
      .sort((a, b) => a.localeCompare(b, 'en'));
    const discoveredSet = new Set(discoveredPageFiles);

    const preferred = preferredPageOrder
      .filter((name) => discoveredSet.has(name))
      .map((name) => `assets/css/pages/${name}`);

    const remaining = discoveredPageFiles
      .filter((name) => !preferredPageOrder.includes(name))
      .map((name) => `assets/css/pages/${name}`);

    pageCssFiles = [...preferred, ...remaining];
  }

  return [...baseCssFiles, ...componentCssFiles, ...pageCssFiles];
}

function bundleCssFromSources() {
  const cssFiles = collectCssFileList();
  let bundledCSS = '';
  let loadedFiles = 0;
  const missingFiles = [];

  for (const file of cssFiles) {
    const filePath = path.join(ROOT_DIR, file);
    if (!fs.existsSync(filePath)) {
      missingFiles.push(file);
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf8');
    if (content.trim().length > 20 && !content.trim().match(/^\/\*.*TODO.*\*\/\s*$/)) {
      bundledCSS += `${content}\n`;
      loadedFiles += 1;
      const fileSize = Buffer.byteLength(content, 'utf8');
      console.log(`   ✅ ${file} 포함 (${(fileSize / 1024).toFixed(2)}KB)`);
    }
  }

  if (loadedFiles === 0) {
    const mainCssPath = path.join(ASSETS_DIR, 'css', 'main.css');
    if (!fs.existsSync(mainCssPath)) {
      throw new Error('No CSS sources found for bundling.');
    }

    console.log('⚠️  분리된 CSS 파일이 없습니다. main.css @import를 inline합니다.');
    const mainContent = fs.readFileSync(mainCssPath, 'utf8');
    bundledCSS = inlineLocalCssImports(mainContent, path.dirname(mainCssPath));
    loadedFiles = 1;
    const bundledSize = Buffer.byteLength(bundledCSS, 'utf8');
    console.log(`   ✅ main.css @import inline (${(bundledSize / 1024).toFixed(2)}KB)`);
  } else if (missingFiles.length > 0) {
    throw new Error(`Required CSS file(s) missing: ${missingFiles.join(', ')}`);
  }

  bundledCSS = inlineLocalCssImports(bundledCSS, path.join(ASSETS_DIR, 'css'));
  const remainingImports = findLocalCssImports(bundledCSS);
  if (remainingImports.length > 0) {
    throw new Error(
      `Bundled CSS still contains local @import: ${remainingImports.map((item) => item.href).join(', ')}`
    );
  }

  return { bundledCSS, loadedFiles };
}

function writeDistMainCss(content) {
  const distCssDir = path.join(DIST_DIR, 'assets', 'css');
  fs.mkdirSync(distCssDir, { recursive: true });
  fs.writeFileSync(path.join(distCssDir, 'main.css'), content);
}

// CSS 통합 및 압축
async function minifyCSS(report) {
  console.log('📦 CSS 통합 및 압축 중...');

  const { bundledCSS, loadedFiles } = bundleCssFromSources();
  console.log(`   ℹ️  총 ${loadedFiles}개 CSS 소스 통합 완료`);

  const originalSize = Buffer.byteLength(bundledCSS, 'utf8');

  try {
    const result = await postcss([cssnano({
      preset: ['default', {
        discardComments: { removeAll: true },
        normalizeWhitespace: true,
      }]
    })]).process(bundledCSS, { from: 'main.css' });

    const minifiedCss = result.css;
    const remainingImports = findLocalCssImports(minifiedCss);
    if (remainingImports.length > 0) {
      throw new Error(
        `Minified CSS still contains local @import: ${remainingImports.map((item) => item.href).join(', ')}`
      );
    }

    writeDistMainCss(minifiedCss);

    const minifiedSize = Buffer.byteLength(minifiedCss, 'utf8');
    const reduction = ((1 - minifiedSize / originalSize) * 100).toFixed(1);

    console.log(`✅ CSS 압축 완료: ${(originalSize / 1024).toFixed(2)}KB → ${(minifiedSize / 1024).toFixed(2)}KB (${reduction}% 감소)`);
  } catch (error) {
    console.error('❌ CSS 압축 실패:', error.message);
    if (report) {
      report.minify.css.fallbackCopied = true;
      report.minify.css.error = error.message;
    }

    writeDistMainCss(bundledCSS);
    console.warn('⚠️  CSS minify 실패 — 통합본을 압축 없이 dist/assets/css/main.css에 저장했습니다.');
  }
}

function addVersionToLocalJsSpecifier(specifier, version) {
  if (!version || typeof specifier !== 'string') return specifier;
  if (specifier.includes('?') || specifier.includes('#')) return specifier;
  if (!/^(?:\.{1,2}\/|\/(?!\/))/.test(specifier)) return specifier;
  if (!specifier.endsWith('.js')) return specifier;
  return `${specifier}?v=${version}`;
}

function applyJsImportVersioning(code, version) {
  if (!version || typeof code !== 'string' || !code.includes('.js')) return code;

  const localJsPath = "((?:\\.{1,2}/|/(?!/))[^\"'?#]+\\.js)";
  const importExportFromPattern = new RegExp(
    `(\\b(?:import|export)\\b[^;]*?\\bfrom\\s*)(["'])${localJsPath}\\2`,
    'g'
  );
  const dynamicImportPattern = new RegExp(
    `(\\bimport\\s*\\(\\s*)(["'])${localJsPath}\\2(\\s*\\))`,
    'g'
  );
  const sideEffectImportPattern = new RegExp(
    `(^|[;\\n\\r])(\\s*import\\s*)(["'])${localJsPath}\\3(?=\\s*;)`,
    'g'
  );

  return code
    .replace(importExportFromPattern, (match, prefix, quote, specifier) => (
      `${prefix}${quote}${addVersionToLocalJsSpecifier(specifier, version)}${quote}`
    ))
    .replace(dynamicImportPattern, (match, prefix, quote, specifier, suffix) => (
      `${prefix}${quote}${addVersionToLocalJsSpecifier(specifier, version)}${quote}${suffix}`
    ))
    .replace(sideEffectImportPattern, (match, boundary, prefix, quote, specifier) => (
      `${boundary}${prefix}${quote}${addVersionToLocalJsSpecifier(specifier, version)}${quote}`
    ));
}

function writeVersionedJsToDist(destPath, code, version) {
  const output = applyJsImportVersioning(code, version);
  fs.writeFileSync(destPath, output);
  return output;
}

// JS 파일 압축하여 dist에 저장 (common.js 등 일부 파일이 없어도 빌드는 계속)
async function minifyJS(report, version) {
  console.log('📦 JS 파일 압축 중...');
  const jsDir = path.join(ASSETS_DIR, 'js');
  const distJsDir = path.join(DIST_DIR, 'assets', 'js');

  if (!fs.existsSync(jsDir)) {
    console.warn('⚠️  assets/js 폴더가 없습니다. JS 압축 단계를 건너뜁니다.');
    return;
  }

  const commonSrc = path.join(jsDir, 'common.js');
  if (!fs.existsSync(commonSrc)) {
    console.warn('⚠️  assets/js/common.js가 없습니다. 공통 스크립트가 필요하면 추가하세요. 빌드는 계속됩니다.');
  }

  // readdir 순서에 따라 파일이 폴더보다 먼저 오면 부모 없이 write 하게 되어 ENOENT가 날 수 있음 — CSS 단계와 동일하게 선생성
  fs.mkdirSync(distJsDir, { recursive: true });
  
  let totalOriginal = 0;
  let totalMinified = 0;
  let processed = 0;
  const bundledFiles = new Set(); // 번들링 제거, 모든 파일 압축
  
  async function processDirectory(srcDir, destDir, baseDir = srcDir) {
    const entries = fs.readdirSync(srcDir, { withFileTypes: true });
    
    for (const entry of entries) {
      const srcPath = path.join(srcDir, entry.name);
      const destPath = path.join(destDir, entry.name);
      const relativePath = path.relative(baseDir, srcPath).replace(/\\/g, '/');
      
      if (entry.isDirectory()) {
        fs.mkdirSync(destPath, { recursive: true });
        await processDirectory(srcPath, destPath, baseDir);
      } else if (entry.isFile() && entry.name.endsWith('.js')) {
        // 병합된 원본 파일은 건너뛰기 (번들 파일만 처리)
        if (bundledFiles.has(relativePath)) {
          continue;
        }

        let code;
        try {
          code = fs.readFileSync(srcPath, 'utf8');
        } catch (readErr) {
          console.warn(`  ⚠️  ${relativePath} 읽기 실패, 건너뜀:`, readErr.message);
          continue;
        }
        const originalSize = Buffer.byteLength(code, 'utf8');
        totalOriginal += originalSize;
        
        try {
          const result = await minify(code, {
            compress: {
              drop_console: true, // 프로덕션 빌드에서 console 제거
              passes: 2,
            },
            mangle: {
              reserved: ['require', 'exports', 'module'],
              properties: false, // 속성 이름 변경 비활성화
            },
            format: {
              comments: false,
            },
          });

          const out = result && typeof result.code === 'string' ? result.code : null;
          if (out == null) {
            const fallbackOut = writeVersionedJsToDist(destPath, code, version);
            console.warn(`  ⚠️  ${relativePath} 압축 결과 없음, 원본 복사`);
            if (report) {
              report.minify.js.fallbackFiles.push({
                file: relativePath,
                reason: 'minifier returned empty output'
              });
            }
            totalMinified += Buffer.byteLength(fallbackOut, 'utf8');
            processed++;
            continue;
          }

          const versionedOut = writeVersionedJsToDist(destPath, out, version);
          
          const minifiedSize = Buffer.byteLength(versionedOut, 'utf8');
          totalMinified += minifiedSize;
          processed++;
          
          const reduction = ((1 - minifiedSize / originalSize) * 100).toFixed(1);
          console.log(`  ✅ ${relativePath}: ${(originalSize / 1024).toFixed(2)}KB → ${(minifiedSize / 1024).toFixed(2)}KB (${reduction}% 감소)`);
        } catch (error) {
          // 압축 실패 시 원본 복사
          const fallbackOut = writeVersionedJsToDist(destPath, code, version);
          console.warn(`  ⚠️  ${relativePath} 압축 실패, 원본 복사:`, error.message);
          if (report) {
            report.minify.js.fallbackFiles.push({
              file: relativePath,
              reason: error.message
            });
          }
          totalMinified += Buffer.byteLength(fallbackOut, 'utf8');
          processed++;
        }
      } else {
        // JS가 아닌 파일은 그대로 복사
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }
  
  // 모든 파일 압축 (번들링 제거)
  try {
    await processDirectory(jsDir, distJsDir, jsDir);
  } catch (err) {
    console.warn('⚠️  JS 디렉터리 처리 중 오류(빌드는 계속):', err.message);
  }
  
  // schedule-manager 관련 코드 제거 (비활성화 - LMS 최적화, 백업: backup/admin/)
  // admin-schedule-manager-new.js → admin-schedule-manager.js 변환 코드 제거됨
  
  const totalReduction = totalOriginal > 0 
    ? ((1 - totalMinified / totalOriginal) * 100).toFixed(1) 
    : 0;
  if (report) {
    report.minify.js.totalProcessed = processed;
  }
  console.log(`\n✅ JS 압축 완료: ${processed}개 파일`);
  console.log(`   총 크기: ${(totalOriginal / 1024).toFixed(2)}KB → ${(totalMinified / 1024).toFixed(2)}KB (${totalReduction}% 감소)`);
}

function recordPreservedOriginal(report, relAssetPath, reason) {
  if (!report) return;
  report.imageOutput.preservedOriginals.push({
    path: `assets/${toPosixPath(relAssetPath)}`,
    reason
  });
}

function recordSkippedOriginal(report, relAssetPath, webpRelPath, reason) {
  if (!report) return;
  const pathValue = `assets/${toPosixPath(relAssetPath)}`;
  if (report.imageOutput.skippedOriginals.some((item) => item.path === pathValue)) return;
  report.imageOutput.skippedOriginals.push({
    path: pathValue,
    output: `assets/${toPosixPath(webpRelPath)}`,
    reason
  });
}

function recordSkippedWebpDuplicate(report, webpRelPath, originalRelPath, reason) {
  if (!report) return;
  const pathValue = `assets/${toPosixPath(webpRelPath)}`;
  if (report.imageOutput.skippedWebpDuplicates.some((item) => item.path === pathValue)) return;
  report.imageOutput.skippedWebpDuplicates.push({
    path: pathValue,
    original: `assets/${toPosixPath(originalRelPath)}`,
    reason
  });
}

function getOriginalSkipReason(relAssetPath) {
  return isWebpPreferredAssetPath(relAssetPath)
    ? 'webp-preferred-display-folder'
    : 'non-allowlisted-original-webp-output-preferred';
}

function getSourceOriginalCounterpartForWebp(relAssetPath) {
  if (path.extname(relAssetPath).toLowerCase() !== '.webp') return '';
  const withoutExt = relAssetPath.replace(/\.webp$/i, '');
  for (const ext of ORIGINAL_RASTER_EXTENSIONS) {
    const candidateRel = `${withoutExt}${ext}`;
    const candidatePath = path.join(ASSETS_DIR, ...candidateRel.split('/'));
    if (fs.existsSync(candidatePath)) {
      return candidateRel;
    }
  }
  return '';
}

function getReferencedAssetPathSet() {
  return new Set(
    collectSourceImageReferences()
      .map((ref) => ref.path.replace(/^assets\//, ''))
  );
}

function shouldEmitWebpForOriginal(relAssetPath, webpRelPath, referencedAssetPaths) {
  const normalizedWebp = toPosixPath(webpRelPath);
  if (FORCED_WEBP_OUTPUTS.has(normalizedWebp)) return true;
  if (referencedAssetPaths && referencedAssetPaths.has(normalizedWebp)) return true;
  return !getOriginalPreserveReason(relAssetPath);
}

function shouldSkipWebpDuplicate(relAssetPath, referencedAssetPaths) {
  const normalized = toPosixPath(relAssetPath);
  if (FORCED_WEBP_OUTPUTS.has(normalized)) return false;
  if (referencedAssetPaths && referencedAssetPaths.has(normalized)) return false;

  const originalRel = getSourceOriginalCounterpartForWebp(normalized);
  return Boolean(originalRel && getOriginalPreserveReason(originalRel));
}

// 이미지 최적화 함수
async function optimizeImage(srcPath, destPath, report, referencedAssetPaths = new Set()) {
  try {
    const stats = fs.statSync(srcPath);
    const ext = path.extname(srcPath).toLowerCase();
    const relAssetPath = getAssetRelativePath(srcPath);
    const imageExtensions = ['.png', '.jpg', '.jpeg', '.webp'];
    
    // 이미지 파일이 아니면 그대로 복사
    if (!imageExtensions.includes(ext)) {
      fs.copyFileSync(srcPath, destPath);
      return { optimized: false, originalSize: stats.size, optimizedSize: stats.size };
    }
    
    // 2MB 이상인 이미지는 경고 및 강제 리사이즈
    const maxFileSize = 2 * 1024 * 1024; // 2MB
    const shouldResize = stats.size > maxFileSize;
    
    if (shouldResize) {
      console.log(`  ⚠️  큰 이미지 감지: ${path.relative(ASSETS_DIR, srcPath)} (${(stats.size / 1024 / 1024).toFixed(2)}MB) - 리사이즈 진행`);
    }
    
    // WebP 파일 최적화
    if (ext === '.webp') {
      if (shouldSkipWebpDuplicate(relAssetPath, referencedAssetPaths)) {
        const originalRelPath = getSourceOriginalCounterpartForWebp(relAssetPath);
        recordSkippedWebpDuplicate(
          report,
          relAssetPath,
          originalRelPath,
          'allowlisted-original-without-runtime-webp-reference'
        );
        return { optimized: false, originalSize: stats.size, optimizedSize: 0, skipped: true };
      }

      const image = sharp(srcPath);
      const metadata = await image.metadata();
      
      // 이미 최적화된 작은 파일은 그대로 복사 (100KB 이하)
      if (stats.size < 100 * 1024) {
        fs.copyFileSync(srcPath, destPath);
        return { optimized: false, originalSize: stats.size, optimizedSize: stats.size };
      }
      
      // 큰 이미지는 리사이즈 후 압축
      let finalWidth = metadata.width;
      let finalHeight = metadata.height;
      
      if (shouldResize && (finalWidth > 2000 || finalHeight > 2000)) {
        if (finalWidth > finalHeight) {
          finalHeight = Math.round((finalHeight * 2000) / finalWidth);
          finalWidth = 2000;
        } else {
          finalWidth = Math.round((finalWidth * 2000) / finalHeight);
          finalHeight = 2000;
        }
        await image
          .resize(finalWidth, finalHeight, { 
            fit: 'inside',
            withoutEnlargement: true 
          })
          .webp({ quality: 80, effort: 6 })
          .toFile(destPath);
      } else {
        // WebP 재압축 (품질 80%, effort 6)
        await image
          .webp({ quality: 80, effort: 6 })
          .toFile(destPath);
      }
      
      const optimizedStats = fs.statSync(destPath);
      const reduction = ((1 - optimizedStats.size / stats.size) * 100).toFixed(1);
      
      if (optimizedStats.size < stats.size) {
        return { 
          optimized: true, 
          originalSize: stats.size, 
          optimizedSize: optimizedStats.size,
          reduction: parseFloat(reduction)
        };
      } else {
        // 압축 후 더 커지면 원본 사용
        fs.copyFileSync(srcPath, destPath);
        return { optimized: false, originalSize: stats.size, optimizedSize: stats.size };
      }
    } 
    // PNG/JPG는 WebP로 변환하고, 정책상 허용된 경우에만 원본을 dist에 보존
    else if (['.png', '.jpg', '.jpeg'].includes(ext)) {
      const webpPath = destPath.replace(/\.(png|jpg|jpeg)$/i, '.webp');
      const webpSrcPath = srcPath.replace(/\.(png|jpg|jpeg)$/i, '.webp');
      const webpRelPath = getWebpRelPath(relAssetPath);
      const preserveReason = getOriginalPreserveReason(relAssetPath);
      
      const shouldEmitWebp = shouldEmitWebpForOriginal(relAssetPath, webpRelPath, referencedAssetPaths);

      // 원본 WebP가 이미 있으면 정책에 따라 WebP도 복사
      if (fs.existsSync(webpSrcPath)) {
        let webpSize = 0;
        if (shouldEmitWebp) {
          fs.copyFileSync(webpSrcPath, webpPath);
          webpSize = fs.statSync(webpPath).size;
        } else {
          recordSkippedWebpDuplicate(
            report,
            webpRelPath,
            relAssetPath,
            'allowlisted-original-without-runtime-webp-reference'
          );
        }
        
        if (preserveReason) {
          fs.copyFileSync(srcPath, destPath);
          recordPreservedOriginal(report, relAssetPath, preserveReason);
        } else {
          recordSkippedOriginal(report, relAssetPath, webpRelPath, getOriginalSkipReason(relAssetPath));
        }
        
        return {
          optimized: shouldEmitWebp,
          originalSize: stats.size,
          optimizedSize: webpSize + (preserveReason ? stats.size : 0),
          converted: shouldEmitWebp
        };
      }

      if (!shouldEmitWebp) {
        if (preserveReason) {
          fs.copyFileSync(srcPath, destPath);
          recordPreservedOriginal(report, relAssetPath, preserveReason);
        }
        recordSkippedWebpDuplicate(
          report,
          webpRelPath,
          relAssetPath,
          'allowlisted-original-without-runtime-webp-reference'
        );
        return {
          optimized: false,
          originalSize: stats.size,
          optimizedSize: preserveReason ? stats.size : 0,
          converted: false
        };
      }
      
      // WebP로 변환 (최대 2000px, 품질 80% - 비용 최적화)
      const image = sharp(srcPath);
      const metadata = await image.metadata();
      
      let width = metadata.width;
      let height = metadata.height;
      
      // 큰 이미지는 리사이즈 (최대 2000px, 2MB 이상이면 더 작게)
      const maxDimension = shouldResize ? 1600 : 2000;
      if (width > maxDimension || height > maxDimension) {
        if (width > height) {
          height = Math.round((height * maxDimension) / width);
          width = maxDimension;
        } else {
          width = Math.round((width * maxDimension) / height);
          height = maxDimension;
        }
      }
      
      await image
        .resize(width, height, { 
          fit: 'inside',
          withoutEnlargement: true 
        })
        .webp({ quality: shouldResize ? 75 : 80, effort: 6 })
        .toFile(webpPath);
      
      const webpStats = fs.statSync(webpPath);
      const reduction = ((1 - webpStats.size / stats.size) * 100).toFixed(1);
      
      if (preserveReason) {
        fs.copyFileSync(srcPath, destPath);
        recordPreservedOriginal(report, relAssetPath, preserveReason);
      } else {
        recordSkippedOriginal(report, relAssetPath, webpRelPath, getOriginalSkipReason(relAssetPath));
      }
      
      return { 
        optimized: true, 
        originalSize: stats.size, 
        optimizedSize: webpStats.size + (preserveReason ? stats.size : 0),
        reduction: parseFloat(reduction),
        converted: true
      };
    } else {
      // 기타 파일은 그대로 복사
      fs.copyFileSync(srcPath, destPath);
      return { optimized: false, originalSize: stats.size, optimizedSize: stats.size };
    }
  } catch (error) {
    const relAssetPath = getAssetRelativePath(srcPath);
    const ext = path.extname(srcPath).toLowerCase();
    const preserveReason = getOriginalPreserveReason(relAssetPath);
    const shouldCopyOriginalOnFailure = !ORIGINAL_RASTER_EXTENSIONS.has(ext) || Boolean(preserveReason);
    console.warn(`  ⚠️  이미지 최적화 실패 (${shouldCopyOriginalOnFailure ? '원본 복사' : '원본 미복사'}): ${path.relative(ASSETS_DIR, srcPath)} - ${error.message}`);
    try {
      if (shouldCopyOriginalOnFailure) {
        fs.copyFileSync(srcPath, destPath);
        if (preserveReason) {
          recordPreservedOriginal(report, relAssetPath, preserveReason);
        }
      }
      const stats = fs.statSync(srcPath);
      return { optimized: false, originalSize: stats.size, optimizedSize: stats.size, error: true };
    } catch (copyError) {
      console.error(`  ❌ 파일 복사 실패: ${srcPath}`, copyError.message);
      return { optimized: false, error: true };
    }
  }
}

function collectLargeDistImages(report) {
  if (!report) return;
  const distAssetsDir = path.join(DIST_DIR, 'assets');
  const distImageFiles = walkFiles(distAssetsDir)
    .filter((filePath) => IMAGE_EXTENSIONS.has(path.extname(filePath).toLowerCase()));

  report.imageOutput.largeDistImages = distImageFiles
    .map((filePath) => {
      const stats = fs.statSync(filePath);
      return {
        path: `dist/${toPosixPath(path.relative(DIST_DIR, filePath))}`,
        sizeBytes: stats.size,
        sizeMB: Number((stats.size / 1024 / 1024).toFixed(2))
      };
    })
    .filter((item) => item.sizeBytes > LARGE_DIST_IMAGE_BYTES)
    .sort((a, b) => b.sizeBytes - a.sizeBytes);
}

function collectAllowedNonWebpDistImages(report) {
  if (!report) return;
  const distAssetsDir = path.join(DIST_DIR, 'assets');
  const distImageFiles = walkFiles(distAssetsDir)
    .filter((filePath) => IMAGE_EXTENSIONS.has(path.extname(filePath).toLowerCase()))
    .filter((filePath) => path.extname(filePath).toLowerCase() !== '.webp');

  report.imageOutput.allowedNonWebpDistFiles = distImageFiles
    .map((filePath) => {
      const relFromAssets = toPosixPath(path.relative(distAssetsDir, filePath));
      const ext = path.extname(relFromAssets).toLowerCase();
      const preserveReason = getOriginalPreserveReason(relFromAssets);
      let reason = preserveReason;
      if (!reason && ext === '.svg') {
        reason = 'vector-image';
      }
      return {
        path: `dist/assets/${relFromAssets}`,
        reason: reason || 'not-allowlisted-review-required'
      };
    })
    .sort((a, b) => a.path.localeCompare(b.path, 'en'));
}

// assets 폴더 복사 및 이미지 최적화
async function copyAssets(report) {
  console.log('📦 assets 폴더 복사 및 이미지 최적화 중...');
  const referencedAssetPaths = getReferencedAssetPathSet();
  
  let totalOriginalSize = 0;
  let totalOptimizedSize = 0;
  let optimizedCount = 0;
  let convertedCount = 0;
  let errorCount = 0;
  
  async function copyDirectory(src, dest) {
    if (!fs.existsSync(src)) {
      return;
    }
    
    fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      
      if (entry.isDirectory()) {
        // css, js는 이미 처리했으므로 스킵
        if (entry.name === 'css' || entry.name === 'js') {
          continue;
        }
        await copyDirectory(srcPath, destPath);
      } else {
        // CSS, JS는 이미 처리했으므로 스킵
        if (entry.name.endsWith('.css') || entry.name.endsWith('.js')) {
          continue;
        }
        
        // 이미지 파일 최적화
        const ext = path.extname(entry.name).toLowerCase();
        if (['.png', '.jpg', '.jpeg', '.webp'].includes(ext)) {
          const result = await optimizeImage(srcPath, destPath, report, referencedAssetPaths);
          if (result && !result.error) {
            totalOriginalSize += result.originalSize;
            totalOptimizedSize += result.optimizedSize;
            if (result.optimized) {
              optimizedCount++;
            }
            if (result.converted) {
              convertedCount++;
            }
          } else if (result && result.error) {
            errorCount++;
          }
        } else {
          // 이미지가 아닌 파일은 그대로 복사
          fs.copyFileSync(srcPath, destPath);
        }
      }
    }
  }
  
  await copyDirectory(ASSETS_DIR, path.join(DIST_DIR, 'assets'));
  collectAllowedNonWebpDistImages(report);
  collectLargeDistImages(report);
  
  const totalReduction = totalOriginalSize > 0 
    ? ((1 - totalOptimizedSize / totalOriginalSize) * 100).toFixed(1)
    : 0;
  const savedBytes = totalOriginalSize - totalOptimizedSize;
  
  console.log(`✅ assets 폴더 복사 및 최적화 완료`);
  if (optimizedCount > 0 || convertedCount > 0) {
    console.log(`   최적화된 이미지: ${optimizedCount}개`);
    if (convertedCount > 0) {
      console.log(`   WebP 변환: ${convertedCount}개`);
    }
    console.log(`   총 크기: ${(totalOriginalSize / 1024 / 1024).toFixed(2)}MB → ${(totalOptimizedSize / 1024 / 1024).toFixed(2)}MB`);
    console.log(`   절감량: ${(savedBytes / 1024 / 1024).toFixed(2)}MB (${totalReduction}% 감소)`);
    console.log(`   💰 예상 대역폭 비용 절감: 약 ${((savedBytes / 1024 / 1024) * 0.12).toFixed(2)}원/GB (월간)`);
  }
  if (errorCount > 0) {
    console.log(`   ⚠️  최적화 실패: ${errorCount}개`);
  }
  if (report && report.imageOutput.largeDistImages.length > 0) {
    console.warn(`   ⚠️  1MB 초과 dist 이미지 ${report.imageOutput.largeDistImages.length}개`);
  }
}

/** 학교 검색용 CSV — assets 루트의 school.csv를 dist로 명시 복사 (누락 방지) */
async function ensureRuntimeWebpInDist(sourceOriginal, runtimeWebp, label) {
  const sourcePath = path.join(ASSETS_DIR, sourceOriginal);
  const runtimePath = path.join(DIST_DIR, 'assets', runtimeWebp);

  if (!fs.existsSync(sourcePath)) {
    throw new Error(`assets/${sourceOriginal} is required as the source original for ${runtimeWebp}.`);
  }

  if (fs.existsSync(runtimePath)) {
    console.log(`✅ ${label} runtime image confirmed: ${runtimeWebp}`);
    return;
  }

  fs.mkdirSync(path.dirname(runtimePath), { recursive: true });
  await sharp(sourcePath)
    .webp({ quality: 80, effort: 6 })
    .toFile(runtimePath);
  console.log(`✅ ${runtimeWebp} generated from assets/${sourceOriginal}`);
}

async function ensureRuntimeWebpImagesInDist() {
  await ensureRuntimeWebpInDist('main.png', 'main.webp', 'Home main visual / OG source');
}

function copySchoolCsvToDist() {
  try {
    const src = path.join(ASSETS_DIR, 'school.csv');
    const dest = path.join(DIST_DIR, 'assets', 'school.csv');
    if (!fs.existsSync(src)) {
      console.warn('⚠️  assets/school.csv 가 없습니다. 회원가입 학교 검색은 동작하지 않을 수 있습니다.');
      return;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    console.log('✅ school.csv → dist/assets/school.csv');
  } catch (e) {
    console.warn('⚠️  school.csv 복사 실패:', e && e.message ? e.message : e);
  }
}

// 버전 번호 생성 (타임스탬프 기반)
function generateVersion() {
  const timestamp = Date.now();
  const date = new Date(timestamp);
  const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
  const timeStr = date.toTimeString().slice(0, 8).replace(/:/g, '');
  return `${dateStr}-${timeStr}`;
}

function escapeHtmlAttribute(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function injectBuildVersionMeta(content, version) {
  const meta = `<meta name="grit-build-version" content="${escapeHtmlAttribute(version)}" />`;
  content = content.replace(/\s*<meta\s+name=["']grit-build-version["'][^>]*>\s*/i, '\n');
  if (/<head[^>]*>/i.test(content)) {
    return content.replace(/<head([^>]*)>/i, `<head$1>\n  ${meta}`);
  }
  return `${meta}\n${content}`;
}

function removeBundledStylesheets(content) {
  return content.replace(
    /\n?\s*<link\b(?=[^>]*\brel=["']stylesheet["'])(?=[^>]*\bhref=["'][^"']*\/assets\/css\/(?:base|components|pages)\/[^"']*\.css(?:\?[^"']*)?["'])[^>]*>\s*/gi,
    '\n'
  );
}

// HTML 파일에 버전 번호 적용
function applyVersionToHTML(content, version) {
  // 기존 버전 쿼리 파라미터 제거 (중복 방지)
  content = content.replace(/[?&]v=[^"'\s&]*/g, '');
  content = removeBundledStylesheets(content);
  content = content.replace(/\/assets\/main\.png/g, '/assets/main.webp');

  content = injectBuildVersionMeta(content, version);
  
  // HTML만 약한 캐시 방지 (서버 헤더가 이미 no-cache이므로 meta는 최소화)
  // 모바일 브라우저를 위한 최소한의 캐시 방지만 추가
  if (!content.includes('http-equiv="Cache-Control"')) {
    content = content.replace(
      /<meta\s+name="viewport"[^>]*>/i,
      (match) => {
        // HTML만 재검증하도록 설정 (CSS/JS는 버전 쿼리 파라미터로 관리)
        // 카카오톡 인앱 브라우저 및 모바일 브라우저 호환성 메타 태그 추가
        return match + '\n  <meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />\n  <meta name="mobile-web-app-capable" content="yes" />\n  <meta name="format-detection" content="telephone=no" />';
      }
    );
  }
  
  // partials는 버전 쿼리 파라미터 추가 (캐시는 유지하되 변경 시 무효화)
  content = content.replace(
    /fetch\(['"]([^'"]*\/assets\/partials\/([^'"]*\.html))['"]\)/g,
    (match, fullUrl, filename) => {
      const separator = fullUrl.includes('?') ? '&' : '?';
      return `fetch('${fullUrl}${separator}v=${version}', { cache: 'default' })`;
    }
  );
  
  // CSS 파일 경로에 버전 추가 (preload 제외)
  content = content.replace(
    /href=["']([^"']*\/assets\/css\/[^"']*\.css)["']/g,
    (match, url) => {
      // 이미 버전이 있으면 스킵
      if (url.includes('v=')) return match;
      const separator = url.includes('?') ? '&' : '?';
      return match.replace(url, `${url}${separator}v=${version}`);
    }
  );
  
  // JS 파일 경로에 버전 추가
  content = content.replace(
    /src=["']([^"']*\/assets\/js\/[^"']*\.js)["']/g,
    (match, url) => {
      // 이미 버전이 있으면 스킵
      if (url.includes('v=')) return match;
      const separator = url.includes('?') ? '&' : '?';
      return match.replace(url, `${url}${separator}v=${version}`);
    }
  );
  
  // preload 링크에도 버전 추가 (CSS/JS)
  content = content.replace(
    /href=["']([^"']*\/assets\/(?:css|js)\/[^"']*)(?:[?&]v=[^"']*)?["']/g,
    (match, url) => {
      // 이미 버전이 있으면 스킵
      if (url.includes('v=')) return match;
      const separator = url.includes('?') ? '&' : '?';
      return match.replace(url, `${url}${separator}v=${version}`);
    }
  );
  
  // 버전 체크 스크립트는 제거됨 (serviceAccountKey.json 의존성 제거)
  // 버전 쿼리 파라미터만 유지하여 캐시 무효화
  
  return content;
}

// HTML 파일 복사 및 개발 코드 제거
function processHTMLFiles(version) {
  console.log('📄 HTML 파일 처리 중...');
  
  const htmlFiles = [
    'index.html',
    'contact.html',
    'course-detail.html',
    'courses.html',
    // 'gallery.html', // 비활성화 - LMS 최적화, 백업: backup/pages/
    'instructor-details.html',
    'instructors.html',
    // 'notice-detail.html', // 비활성화 - LMS 최적화, 백업: backup/pages/
    // 'notice.html', // 비활성화 - LMS 최적화, 백업: backup/pages/
    'privacy.html',
    // 'qna.html', // 비활성화 - LMS 최적화, 백업: backup/pages/
    'schedule.html',
    'schedule-images.html',
    'story.html',
    'terms.html',
    'tuition.html',
    '404.html'
  ];
  
  // members 폴더의 HTML 파일들
  const membersDir = path.join(ROOT_DIR, 'members');
  if (fs.existsSync(membersDir)) {
    function findHtmlFiles(dir, basePath = '') {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        const relativePath = path.join(basePath, entry.name);
        if (entry.isDirectory()) {
          findHtmlFiles(fullPath, relativePath);
        } else if (entry.name.endsWith('.html')) {
          htmlFiles.push(path.join('members', relativePath));
        }
      }
    }
    findHtmlFiles(membersDir);
  }
  
  let processed = 0;
  const devCodePattern = /<!-- 개발 환경 감지 및 캐시 우회[^]*?}\)\(\);\s*<\/script>/;
  
  htmlFiles.forEach(htmlFile => {
    const srcPath = path.join(ROOT_DIR, htmlFile);
    if (!fs.existsSync(srcPath)) {
      return;
    }
    
    try {
      let content = fs.readFileSync(srcPath, 'utf8');
      
      // 개발 환경 코드 제거
      if (devCodePattern.test(content)) {
        content = content.replace(devCodePattern, '');
        processed++;
      }
      
      // 버전 번호 적용
      content = applyVersionToHTML(content, version);
      
      const destPath = path.join(DIST_DIR, htmlFile);
      const destDir = path.dirname(destPath);
      fs.mkdirSync(destDir, { recursive: true });
      
      try {
        if (!writeDistFileSafely(destPath, content)) {
          console.warn(`⚠️  ${htmlFile} 쓰기 실패 (파일이 사용 중일 수 있음)`);
        }
      } catch (writeErr) {
        console.warn(`⚠️  ${htmlFile} 쓰기 실패 (파일이 사용 중일 수 있음): ${writeErr.message}`);
      }

      if (htmlFile === 'schedule-images.html') {
        writeScheduleImagesCleanUrlContent(content);
      }
    } catch (err) {
      console.warn(`⚠️  ${htmlFile} 처리 실패: ${err.message}`);
      // 계속 진행
    }
  });
  
  // schedule-manager 관련 코드 제거 (비활성화 - LMS 최적화, 백업: backup/admin/)
  // schedule-manager-new.html → schedule-manager.html 변환 코드 제거됨
  
  console.log(`✅ HTML 파일 처리 완료: ${htmlFiles.length}개 파일 (${processed}개에서 개발 코드 제거)`);
  console.log(`   버전 번호: ${version}`);
}

/** @deprecated schedule-images clean URL is written during processHTMLFiles */
function writeScheduleImagesCleanUrl() {
  const sourcePath = path.join(DIST_DIR, 'schedule-images.html');
  const destPath = path.join(DIST_DIR, 'schedule-images', 'index.html');
  if (distPathAccessible(destPath)) return;
  if (!fs.existsSync(sourcePath)) {
    console.warn('⚠️  schedule-images.html 없음 — /schedule-images clean URL 생략');
    return;
  }
  const content = fs.readFileSync(sourcePath, 'utf8');
  writeScheduleImagesCleanUrlContent(content);
}

// data 폴더 복사
function copyData() {
  console.log('📦 data 폴더 복사 중...');
  const dataDir = path.join(ROOT_DIR, 'data');
  const distDataDir = path.join(DIST_DIR, 'data');
  
  if (fs.existsSync(dataDir)) {
    fs.cpSync(dataDir, distDataDir, { recursive: true });
    console.log('✅ data 폴더 복사 완료');
  } else {
    console.log('ℹ️  data 폴더 없음');
  }
}

function getCurrentDateYmd() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function generateSitemapXml() {
  const baseUrl = 'https://gritedu.kr';
  const lastmod = getCurrentDateYmd();
  const pages = [
    { path: '/', priority: '1.0' },
    { path: '/courses.html', priority: '0.9' },
    { path: '/instructors.html', priority: '0.9' },
    { path: '/contact.html', priority: '0.9' },
    { path: '/story.html', priority: '0.8' },
    { path: '/schedule.html', priority: '0.5' },
  ];

  const urlEntries = pages.map((page) => {
    const loc = `${baseUrl}${page.path}`;
    return [
      '  <url>',
      `    <loc>${loc}</loc>`,
      `    <lastmod>${lastmod}</lastmod>`,
      `    <priority>${page.priority}</priority>`,
      '  </url>'
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urlEntries,
    '</urlset>',
    ''
  ].join('\n');
}

// Cloudflare Pages/Firebase Hosting에서 공통으로 필요한 공개 메타 파일 생성
function copyConfigFiles(version) {
  console.log('📦 공개 설정 파일 생성 중...');
  const robotsPath = path.join(ROOT_DIR, 'robots.txt');

  const distSitemapPath = path.join(DIST_DIR, 'sitemap.xml');
  const sitemapXml = generateSitemapXml();
  fs.writeFileSync(distSitemapPath, sitemapXml, 'utf8');
  console.log('✅ sitemap.xml 자동 생성 완료');

  writeVersionJson(version);
  writeCloudflarePagesHeaders();
  writeCloudflareRedirects();

  if (fs.existsSync(robotsPath)) {
    fs.copyFileSync(robotsPath, path.join(DIST_DIR, 'robots.txt'));
    console.log('✅ robots.txt 복사 완료');
  } else {
    console.log('ℹ️  robots.txt 없음');
  }
}

// Search Console / 네이버 서치어드바이저 등 — 루트에 받은 소유 확인용 HTML을 dist 루트로 복사
// (processHTMLFiles 는 사이트 페이지만 화이트리스트로 복사하므로 여기서 따로 처리)
function copySearchVerificationHtmlFiles() {
  console.log('📦 검색엔진 소유 확인(HTML) 복사 중...');
  let copied = 0;
  const entries = fs.readdirSync(ROOT_DIR, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isFile() || !e.name.endsWith('.html')) continue;
    const lower = e.name.toLowerCase();
    if (!lower.startsWith('google') && !lower.startsWith('naver')) continue;
    const src = path.join(ROOT_DIR, e.name);
    const dest = path.join(DIST_DIR, e.name);
    fs.copyFileSync(src, dest);
    console.log(`   ✅ ${e.name} → dist/${e.name}`);
    copied++;
  }
  if (copied === 0) {
    console.log('   ℹ️  루트에 google*.html / naver*.html 없음');
  }
}

function copyPwaRuntimeFiles() {
  console.log('📦 PWA Lite 런타임 파일 복사 중...');
  const pwaFiles = [
    'manifest.webmanifest',
    'sw.js',
    'offline.html'
  ];

  for (const fileName of pwaFiles) {
    const src = path.join(ROOT_DIR, fileName);
    const dest = path.join(DIST_DIR, fileName);

    if (!fs.existsSync(src)) {
      console.warn(`   ⚠️  ${fileName} 없음`);
      continue;
    }

    fs.copyFileSync(src, dest);
    console.log(`   ✅ ${fileName} → dist/${fileName}`);
  }
}

// 빌드 통계
function printStats() {
  console.log('\n📊 빌드 통계:');
  
  function getDirSize(dir) {
    let size = 0;
    if (!fs.existsSync(dir)) return 0;
    
    try {
      const files = fs.readdirSync(dir, { withFileTypes: true });
      for (const file of files) {
        const filePath = path.join(dir, file.name);
        try {
          if (file.isDirectory()) {
            size += getDirSize(filePath);
          } else {
            size += fs.statSync(filePath).size;
          }
        } catch (err) {
          // 파일 접근 권한 오류 시 건너뛰기
          if (err.code === 'EPERM' || err.code === 'EACCES') {
            continue;
          }
          throw err;
        }
      }
    } catch (err) {
      // 디렉토리 읽기 권한 오류 시 0 반환
      if (err.code === 'EPERM' || err.code === 'EACCES') {
        return 0;
      }
      throw err;
    }
    return size;
  }
  
  const distSize = getDirSize(DIST_DIR);
  console.log(`  빌드 산출물: ${(distSize / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  위치: ${DIST_DIR}`);
}

// Node 구버전 호환: fs.readdirSync(…, { recursive: true }) 미지원 환경 대비
function collectHtmlRelativePaths(dir, basePath = '') {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const rel = path.join(basePath, entry.name);
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === '.git') continue;
      out.push(...collectHtmlRelativePaths(full, rel));
    } else if (entry.name.endsWith('.html')) {
      out.push(rel.split(path.sep).join('/'));
    }
  }
  return out;
}

// 메인 실행 — 단계별 실패 시에도 가능한 한 dist를 채움
async function prebuild() {
  const args = process.argv.slice(2);
  
  // --no-dev-remove 옵션: 개발 코드 제거 안 함
  const removeDev = !args.includes('--no-dev-remove');
  const strictMode = args.includes('--strict');
  
  console.log('🚀 배포 전 빌드 시작...\n');
  console.log('📌 원본 파일은 그대로 유지됩니다.\n');
  if (strictMode) {
    console.log('🧪 strict 모드 활성화: minify 실패/폴백/경고가 있으면 빌드를 실패 처리합니다.\n');
  }
  
  let stepWarnings = 0;
  let buildReport = null;

  function warnStep(name, err) {
    stepWarnings++;
    const message = err && err.message ? err.message : String(err);
    console.warn(`⚠️  [${name}] ${message}`);
    if (buildReport) {
      buildReport.steps.warnings.push({ step: name, message });
    }
  }

  try {
    const version = generateVersion();
    buildReport = createBuildReport({ strictMode, removeDev, version });
    console.log(`📌 빌드 버전: ${version}\n`);
    
    try {
      initDistDir();
    } catch (e) {
      warnStep('dist 초기화', e);
      if (!fs.existsSync(DIST_DIR)) {
        fs.mkdirSync(DIST_DIR, { recursive: true });
      }
    }
    
    try {
      validateImageAssetPolicy(buildReport);
    } catch (e) {
      warnStep('image asset validation', e);
    }

    try {
      await minifyCSS(buildReport);
    } catch (e) {
      warnStep('CSS 압축', e);
      try {
        const { bundledCSS } = bundleCssFromSources();
        writeDistMainCss(bundledCSS);
        console.log('   ℹ️  통합 CSS를 dist/assets/css/main.css에 저장했습니다.');
      } catch (fallbackErr) {
        warnStep('CSS 폴백 저장', fallbackErr);
      }
    }
    
    try {
      await minifyJS(buildReport, version);
    } catch (e) {
      warnStep('JS 압축', e);
    }
    
    try {
      await copyAssets(buildReport);
    } catch (e) {
      warnStep('assets 복사/이미지', e);
    }

    try {
      await ensureRuntimeWebpImagesInDist();
    } catch (e) {
      warnStep('runtime WebP 이미지 보장', e);
    }

    try {
      copySchoolCsvToDist();
    } catch (e) {
      warnStep('school.csv', e);
    }
    
    try {
      if (removeDev) {
        processHTMLFiles(version);
      } else {
        console.log('ℹ️  개발 환경 코드 제거 건너뜀 (--no-dev-remove)');
        const htmlFiles = collectHtmlRelativePaths(ROOT_DIR).filter(
          (f) => !f.includes('node_modules')
        );
        htmlFiles.forEach(htmlFile => {
          try {
            const srcPath = path.join(ROOT_DIR, htmlFile);
            const destPath = path.join(DIST_DIR, htmlFile);
            const destDir = path.dirname(destPath);
            fs.mkdirSync(destDir, { recursive: true });
            let content = fs.readFileSync(srcPath, 'utf8');
            content = applyVersionToHTML(content, version);
            fs.writeFileSync(destPath, content);
          } catch (fileErr) {
            warnStep(`HTML ${htmlFile}`, fileErr);
          }
        });
        console.log(`✅ HTML 파일 복사 완료: ${htmlFiles.length}개 파일`);
        console.log(`   버전 번호: ${version}`);
      }
    } catch (e) {
      warnStep('HTML 처리', e);
    }
    
    try {
      copyData();
    } catch (e) {
      warnStep('data 복사', e);
    }
    
    try {
      copyConfigFiles(version);
    } catch (e) {
      warnStep('설정 파일 복사', e);
    }

    try {
      copyPwaRuntimeFiles();
    } catch (e) {
      warnStep('PWA Lite 런타임 파일 복사', e);
    }

    try {
      copySearchVerificationHtmlFiles();
    } catch (e) {
      warnStep('검색 소유 확인 HTML 복사', e);
    }
    
    try {
      removeSensitiveDistFiles();
    } catch (e) {
      warnStep('public 제외 대상 정리', e);
    }

    try {
      printStats();
    } catch (e) {
      warnStep('통계 출력', e);
    }
    
    const indexPath = path.join(DIST_DIR, 'index.html');
    if (!fs.existsSync(indexPath)) {
      console.error('❌ dist/index.html 이 없습니다. HTML 소스 경로를 확인하세요.');
      process.exit(1);
    }

    const jsFallbackFiles = buildReport.minify.js.fallbackFiles;
    const hasCssFallback = buildReport.minify.css.fallbackCopied;
    if (hasCssFallback) {
      console.warn('⚠️  CSS minify 실패로 통합본이 압축 없이 dist에 저장되었습니다.');
      if (buildReport.minify.css.error) {
        console.warn(`   원인: ${buildReport.minify.css.error}`);
      }
    }
    if (jsFallbackFiles.length > 0) {
      console.warn(`⚠️  JS minify 실패 파일 ${jsFallbackFiles.length}개가 원본으로 복사되었습니다:`);
      jsFallbackFiles.forEach(({ file, reason }) => {
        console.warn(`   - ${file}: ${reason}`);
      });
    }

    const hasStrictFailures = stepWarnings > 0 || hasCssFallback || jsFallbackFiles.length > 0;
    buildReport.steps.totalWarnings = stepWarnings;
    writeBuildReport(buildReport);
    if (strictMode && hasStrictFailures) {
      console.error('\n❌ strict 빌드 실패: 경고 또는 minify 폴백이 감지되었습니다.');
      console.error(`   빌드 리포트 확인: ${path.join(DIST_DIR, BUILD_REPORT_FILENAME)}`);
      process.exit(1);
    }

    console.log(`\n📁 빌드 산출물: ${DIST_DIR}`);
    console.log(`📌 빌드 버전: ${version}`);
    if (stepWarnings > 0) {
      console.warn(`\n⚠️  일부 단계에서 경고 ${stepWarnings}건 — dist는 생성되었으나 내용을 확인하세요.`);
    } else {
      console.log('\n✅ 빌드 완료! 배포 준비되었습니다.');
    }
    console.log('💡 원본 파일은 그대로 유지되었습니다.');
  } catch (error) {
    console.error('❌ 빌드 치명적 실패:', error);
    process.exit(1);
  }
}

prebuild();
